### ISSUE TITLE
How to escape format?

### ISSUE THREAD

**Issue by happyfloat** [dayjs/day.dart#35]
In dayjs you can do something like this:

```js
dayjs('2019-01-25').format('[YYYYescape] YYYY-MM-DDTHH:mm:ssZ[Z]') 
// 'YYYYescape 2019-01-25T00:00:00-02:00Z'
```

Is it possible to escape some parts of the format string in this dart version too? Thanks!

**Comment by g1eny0ung** [comment]
I do not add this feature currently. But it's ez to implement.

I will add this feature in these two days.

**Comment by g1eny0ung** [comment]
Finish in [0.5.5](https://pub.dev/packages/day).
