### ISSUE TITLE
Support relative formatting

### ISSUE THREAD

**Issue by chimon2000** [dayjs/day.dart#36]
Support for the same relative time functions as dayjs.

1. fromNow
2. from
3. to
4. toNow

**Comment by g1eny0ung** [comment]
I will try to add this plugin this weekend.

**Comment by g1eny0ung** [comment]
@chimon2000 Finished in [v0.6.0](https://pub.dev/packages/day).

Here is the doc: https://github.com/dayjs/day.dart/blob/master/PLUGINS.md#relative-time

**Comment by chimon2000** [comment]
Awesome!
