### ISSUE TITLE
question

### ISSUE THREAD

**Issue by chitgoks** [dayjs/day.dart#37]
this is sample string date

2021-02-04T02:00:40
I do 

```
Day day = Day.fromString(activity.dateCreated);
      day.setHour(0);
      day.setMinute(0);
      day.setSecond(0);
```

print(day);
outputs 2021-02-04 02:00:40.000

The time is not 0. thoughts?

**Comment by g1eny0ung** [comment]
It needs to call the`.finished()` method to update all the modifications. This was designed as a chain setting.

Ref: https://github.com/dayjs/day.dart/blob/master/API.md#set-setstring-unit-int-val.

**Comment by chitgoks** [comment]
ahhh i didnt see the hour(), minute() and second() functions. thank you.
